### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by ltybc138** [gooddaytoday/TypeScript-Handbook-RU#23]

**Comment by gooddaytoday** [comment]
Уже переведено

**Comment by ltybc138** [comment]
Так, хорошо, а что не переведено?

понедельник, 22 августа 2016 г. пользователь George Kiselev написал:

**Comment by gooddaytoday** [comment]
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Compiler%20Options.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Declaration%20Merging.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Iterators%20and%20Generators.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Mixins.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Module%20Resolution.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Modules.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Namespaces%20and%20Modules.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Namespaces.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/blob/master/pages/Triple-Slash%20Directives.md
https://github.com/gooddaytoday/TypeScript-Handbook-RU/tree/master/pages/declaration%20files
https://github.com/gooddaytoday/TypeScript-Handbook-RU/tree/master/pages/tutorials
