### ISSUE TITLE
Genetics

### ISSUE THREAD

**Issue by ltybc138** [gooddaytoday/TypeScript-Handbook-RU#24]

**Comment by gooddaytoday** [comment]
Если имелось в виду Generics, это уже переведено

**Comment by ltybc138** [comment]
С functions я вовремя остановился(вернее не успел начать, текст уже был
переведен). Но generics не был переведен и не было issue.


2016-08-22 17:07 GMT+05:00 George Kiselev <notifications@github.com>:

**Comment by zenwarr** [comment]
> С functions я вовремя остановился(вернее не успел начать, текст уже был переведен). Но generics не был переведен и не было issue.

Было. #12
